// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import HomeOutlined from 'D:/code/github/basic_knowledge_base/code-station/backend/node_modules/@ant-design/icons/es/icons/HomeOutlined';
import UserOutlined from 'D:/code/github/basic_knowledge_base/code-station/backend/node_modules/@ant-design/icons/es/icons/UserOutlined';
import TeamOutlined from 'D:/code/github/basic_knowledge_base/code-station/backend/node_modules/@ant-design/icons/es/icons/TeamOutlined';
import ReadOutlined from 'D:/code/github/basic_knowledge_base/code-station/backend/node_modules/@ant-design/icons/es/icons/ReadOutlined';
import EditOutlined from 'D:/code/github/basic_knowledge_base/code-station/backend/node_modules/@ant-design/icons/es/icons/EditOutlined';
import ProfileOutlined from 'D:/code/github/basic_knowledge_base/code-station/backend/node_modules/@ant-design/icons/es/icons/ProfileOutlined';
import CalendarOutlined from 'D:/code/github/basic_knowledge_base/code-station/backend/node_modules/@ant-design/icons/es/icons/CalendarOutlined';
import AppstoreOutlined from 'D:/code/github/basic_knowledge_base/code-station/backend/node_modules/@ant-design/icons/es/icons/AppstoreOutlined';
export default { HomeOutlined, UserOutlined, TeamOutlined, ReadOutlined, EditOutlined, ProfileOutlined, CalendarOutlined, AppstoreOutlined };
