// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { connect, useDispatch, useStore, useSelector } from 'D:/code/github/basic_knowledge_base/code-station/backend/node_modules/@umijs/plugins/libs/dva.tsx';
export { getDvaApp } from './dva';
