// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import model_1 from 'D:/code/github/basic_knowledge_base/code-station/backend/src/models/adminModel';

export const models = {
model_1: { namespace: 'adminModel', model: model_1 },
} as const
